# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161027_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='creationDate',
            new_name='creation_date',
        ),
    ]
