# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161029_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-creationDate']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-creationDate']},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='creation_date',
            new_name='creationDate',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='creation_date',
            new_name='creationDate',
        ),
    ]
