# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161029_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
