# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_album_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='private',
        ),
        migrations.AddField(
            model_name='photo',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
