# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20161104_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='private',
        ),
        migrations.AddField(
            model_name='album',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
